// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import path from "path"
import { fileURLToPath } from "url"
import { config } from "dotenv"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

config({ path: path.resolve(process.cwd(), '.env') })
config({ path: path.resolve(__dirname, '.env') })
config({ path: path.resolve(process.cwd(), '../.env') })

const dbUrl = process.env.DATABASE_URL || "mysql://istrac_user:IstracSecurePass123!@127.0.0.1:3306/istrac_fms"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'node dist/prisma/seed.js'
  },
  datasource: {
    url: dbUrl,
    shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL,
  },
});
